# Generated by Django 4.2.4 on 2023-08-19 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=455)),
                ('phone_number', models.CharField(default='', max_length=455)),
                ('email_address', models.CharField(default='', max_length=455)),
                ('created_data', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
